language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist

script:
  - vendor/bin/tester tests/ -C

notifications:
  email: false
